### PR TITLE
Make .npmignore more comprehensive

### LINKED ISSUE #851: Don't publish regression PNGs to npm

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Fixes #851

Change-type: patch
Signed-off-by: Lucian <lucian.buzzo@gmail.com>

### CODE REVIEW

**Comment by thgreasi** [comment]
@lucianbuzzo, maybe we could simply have a
```
"files": [
  "dist/",
  "docs/"
],
```
section in the package.json

**Comment by thgreasi** [comment]
Here is the output:
```
npm notice 5.8kB  package.json                                                    
npm notice 35.1kB CHANGELOG.md                                                    
npm notice 11.3kB LICENSE                                                         
npm notice 49.2kB README.md                                                       
npm notice 517B   dist/asRendition.d.ts                                           
npm notice 3.7kB  dist/asRendition.js                                             
npm notice 3.0kB  dist/common-types.d.ts                                          
npm notice 77B    dist/common-types.js                                            
npm notice 467B   dist/components/Alert.d.ts                                      
npm notice 8.6kB  dist/components/Alert.js                                        
npm notice 673B   dist/components/ArcSlider.d.ts                                  
npm notice 9.2kB  dist/components/ArcSlider.js                                    
npm notice 531B   dist/components/Badge.d.ts                                      
npm notice 2.9kB  dist/components/Badge.js                                        
npm notice 341B   dist/components/Banner.d.ts                                     
npm notice 1.5kB  dist/components/Banner.js                                       
npm notice 796B   dist/components/Button.d.ts                                     
npm notice 7.0kB  dist/components/Button.js                                       
npm notice 284B   dist/components/ButtonGroup.d.ts                                
npm notice 1.2kB  dist/components/ButtonGroup.js                                  
npm notice 434B   dist/components/Card.d.ts                                       
npm notice 3.0kB  dist/components/Card.js                                         
npm notice 533B   dist/components/Container.d.ts                                  
npm notice 1.7kB  dist/components/Container.js                                    
npm notice 1.6kB  dist/components/DataTypes/array.d.ts                            
npm notice 4.2kB  dist/components/DataTypes/array.js                              
npm notice 905B   dist/components/DataTypes/boolean.d.ts                          
npm notice 2.6kB  dist/components/DataTypes/boolean.js                            
npm notice 160B   dist/components/DataTypes/date-time-helpers.d.ts                
npm notice 483B   dist/components/DataTypes/date-time-helpers.js                  
npm notice 1.3kB  dist/components/DataTypes/date-time.d.ts                        
npm notice 3.9kB  dist/components/DataTypes/date-time.js                          
npm notice 1.1kB  dist/components/DataTypes/enum.d.ts                             
npm notice 3.1kB  dist/components/DataTypes/enum.js                               
npm notice 543B   dist/components/DataTypes/index.d.ts                            
npm notice 1.0kB  dist/components/DataTypes/index.js                              
npm notice 1.3kB  dist/components/DataTypes/number.d.ts                           
npm notice 3.5kB  dist/components/DataTypes/number.js                             
npm notice 2.3kB  dist/components/DataTypes/object.d.ts                           
npm notice 9.9kB  dist/components/DataTypes/object.js                             
npm notice 1.1kB  dist/components/DataTypes/oneOf.d.ts                            
npm notice 3.3kB  dist/components/DataTypes/oneOf.js                              
npm notice 1.8kB  dist/components/DataTypes/string.d.ts                           
npm notice 6.0kB  dist/components/DataTypes/string.js                             
npm notice 529B   dist/components/Divider.d.ts                                    
npm notice 884B   dist/components/Divider.js                                      
npm notice 1.1kB  dist/components/DropDownButton.d.ts                             
npm notice 10.1kB dist/components/DropDownButton.js                               
npm notice 337B   dist/components/Filters/FilterDescription.d.ts                  
npm notice 2.4kB  dist/components/Filters/FilterDescription.js                    
npm notice 3.4kB  dist/components/Filters/index.d.ts                              
npm notice 17.1kB dist/components/Filters/index.js                                
npm notice 1.1kB  dist/components/Filters/SchemaSieve.d.ts                        
npm notice 7.9kB  dist/components/Filters/SchemaSieve.js                          
npm notice 882B   dist/components/Filters/Summary.d.ts                            
npm notice 5.2kB  dist/components/Filters/Summary.js                              
npm notice 891B   dist/components/Filters/ViewsMenu.d.ts                          
npm notice 7.7kB  dist/components/Filters/ViewsMenu.js                            
npm notice 694B   dist/components/Fixed.d.ts                                      
npm notice 1.6kB  dist/components/Fixed.js                                        
npm notice 827B   dist/components/Grid.d.ts                                       
npm notice 1.3kB  dist/components/Grid.js                                         
npm notice 692B   dist/components/Heading.d.ts                                    
npm notice 2.1kB  dist/components/Heading.js                                      
npm notice 285B   dist/components/Img.d.ts                                        
npm notice 796B   dist/components/Img.js                                          
npm notice 1.1kB  dist/components/Input.d.ts                                      
npm notice 3.0kB  dist/components/Input.js                                        
npm notice 563B   dist/components/Link.d.ts                                       
npm notice 2.9kB  dist/components/Link.js                                         
npm notice 4.7kB  dist/components/Modal.d.ts                                      
npm notice 6.9kB  dist/components/Modal.js                                        
npm notice 488B   dist/components/Navbar.d.ts                                     
npm notice 5.2kB  dist/components/Navbar.js                                       
npm notice 376B   dist/components/Pager.d.ts                                      
npm notice 2.6kB  dist/components/Pager.js                                        
npm notice 551B   dist/components/ProgressBar.d.ts                                
npm notice 5.0kB  dist/components/ProgressBar.js                                  
npm notice 266B   dist/components/Provider.d.ts                                   
npm notice 2.0kB  dist/components/Provider.js                                     
npm notice 454B   dist/components/Search.d.ts                                     
npm notice 2.5kB  dist/components/Search.js                                       
npm notice 476B   dist/components/Select.d.ts                                     
npm notice 3.9kB  dist/components/Select.js                                       
npm notice 1.9kB  dist/components/Table/index.d.ts                                
npm notice 17.4kB dist/components/Table/index.js                                  
npm notice 1.0kB  dist/components/Table/TableRow.d.ts                             
npm notice 2.9kB  dist/components/Table/TableRow.js                               
npm notice 279B   dist/components/Tabs.d.ts                                       
npm notice 1.4kB  dist/components/Tabs.js                                         
npm notice 858B   dist/components/Terminal/index.d.ts                             
npm notice 5.2kB  dist/components/Terminal/index.js                               
npm notice 1.8kB  dist/components/Terminal/XTermDefaultStyle.d.ts                 
npm notice 1.8kB  dist/components/Terminal/XTermDefaultStyle.js                   
npm notice 827B   dist/components/Textarea.d.ts                                   
npm notice 2.8kB  dist/components/Textarea.js                                     
npm notice 495B   dist/components/TextWithCopy.d.ts                               
npm notice 4.4kB  dist/components/TextWithCopy.js                                 
npm notice 1.2kB  dist/components/Txt.d.ts                                        
npm notice 2.0kB  dist/components/Txt.js                                          
npm notice 11B    dist/extra/Form/markdown.d.ts                                   
npm notice 3.9kB  dist/extra/Form/markdown.js                                     
npm notice 11B    dist/extra/Form/mermaid.d.ts                                    
npm notice 3.9kB  dist/extra/Form/mermaid.js                                      
npm notice 243B   dist/extra/Markdown.d.ts                                        
npm notice 26.6kB dist/extra/Markdown.js                                          
npm notice 513B   dist/extra/Mermaid.d.ts                                         
npm notice 3.0kB  dist/extra/Mermaid.js                                           
npm notice 2.9kB  dist/index.d.ts                                                 
npm notice 3.1kB  dist/index.js                                                   
npm notice 1.9kB  dist/migration-types.d.ts                                       
npm notice 77B    dist/migration-types.js                                         
npm notice 663B   dist/migrations.d.ts                                            
npm notice 8.5kB  dist/migrations.js                                              
npm notice 3.1kB  dist/theme.d.ts                                                 
npm notice 3.8kB  dist/theme.js                                                   
npm notice 573B   dist/tooltips.d.ts                                              
npm notice 12.7kB dist/tooltips.js                                                
npm notice 1.5kB  dist/unstable/components/Async.d.ts                             
npm notice 1.9kB  dist/unstable/components/Async.js                               
npm notice 176B   dist/unstable/components/Form/fields/DescriptionField.d.ts      
npm notice 524B   dist/unstable/components/Form/fields/DescriptionField.js        
npm notice 1.9kB  dist/unstable/components/Form/fields/ObjectField.d.ts           
npm notice 10.3kB dist/unstable/components/Form/fields/ObjectField.js             
npm notice 943B   dist/unstable/components/Form/fields/PatternPropertiesField.d.ts
npm notice 4.9kB  dist/unstable/components/Form/fields/PatternPropertiesField.js  
npm notice 331B   dist/unstable/components/Form/fields/TitleField.d.ts            
npm notice 1.4kB  dist/unstable/components/Form/fields/TitleField.js              
npm notice 606B   dist/unstable/components/Form/index.d.ts                        
npm notice 6.3kB  dist/unstable/components/Form/index.js                          
npm notice 105B   dist/unstable/components/Form/LabelElement.d.ts                 
npm notice 757B   dist/unstable/components/Form/LabelElement.js                   
npm notice 195B   dist/unstable/components/Form/templates/ArrayFieldTemplate.d.ts 
npm notice 4.0kB  dist/unstable/components/Form/templates/ArrayFieldTemplate.js   
npm notice 499B   dist/unstable/components/Form/templates/FieldTemplate.d.ts      
npm notice 1.9kB  dist/unstable/components/Form/templates/FieldTemplate.js        
npm notice 219B   dist/unstable/components/Form/templates/ObjectFieldTemplate.d.ts
npm notice 776B   dist/unstable/components/Form/templates/ObjectFieldTemplate.js  
npm notice 123B   dist/unstable/components/Form/WarningField.d.ts                 
npm notice 443B   dist/unstable/components/Form/WarningField.js                   
npm notice 185B   dist/unstable/components/Form/widgets/BaseInput.d.ts            
npm notice 2.1kB  dist/unstable/components/Form/widgets/BaseInput.js              
npm notice 225B   dist/unstable/components/JellyForm/formulas.d.ts                
npm notice 2.6kB  dist/unstable/components/JellyForm/formulas.js                  
npm notice 529B   dist/unstable/components/JellyForm/index.d.ts                   
npm notice 3.8kB  dist/unstable/components/JellyForm/index.js                     
npm notice 127B   dist/unstable/index.d.ts                                        
npm notice 392B   dist/unstable/index.js                                          
npm notice 1.3kB  dist/unstable/unstable-typings.d.ts                             
npm notice 77B    dist/unstable/unstable-typings.js                               
npm notice 1.9kB  dist/utils.d.ts                                                 
npm notice 4.1kB  dist/utils.js                                                   
npm notice 5.3kB  docs/_README.tpl.md                                             
npm notice 4.1kB  docs/COMMIT-GUIDELINES.md                                       
npm notice 4.4kB  docs/CONTRIBUTING.md                                            
npm notice 2.1kB  docs/migrating_3x-4x.md                                         
npm notice 287B   docs/migrating_4x-5x.md                                         
npm notice 1.6kB  docs/migrating_6x-7x.md 
```

**Comment by thgreasi** [comment]
Opened https://github.com/balena-io-modules/rendition/pull/853 for comparison.

**Comment by LucianBuzzo** [comment]
closing in favour of https://github.com/balena-io-modules/rendition/pull/853

**Pull request closed without merging**
