### PR TITLE
Link headings in markdown

### PR DESCRIPTION
**Pull request by iamsolankiamit**
Change-type: minor
Signed-off-by: Amit Solanki <amit@balena.io>

### CODE REVIEW

**Comment by LucianBuzzo** [comment]
@iamsolankiamit Does this plugin create anchor links for headings? Is there an instance where we would not want this behaviour? It seems really useful.

**Comment by iamsolankiamit** [comment]
@LucianBuzzo made it optional, since i don't know how and where this might affect in jellyfish. If you think it won't affect (like adding anchor tags and ids in chat maybe?) any of those projects, then i'll flip the condition to optionally disable adding links and ids to headings.

**Comment by LucianBuzzo** [comment]
@iamsolankiamit I think we should make it the standard, and remove the option. If we have a really strong reason we can always make it optional later. We should push back quite hard on adding new options, as it leads to a combinatorial explosion of potential outputs, and also potential errors.

**Comment by iamsolankiamit** [comment]
@balena-ci I self-certify!

**Pull request merged**
