### PR TITLE
Form: Allow markdown in description fields

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Change-type: minor
Signed-off-by: Lucian <lucian.buzzo@gmail.com>

### CODE REVIEW

**Comment by JackuB** [comment]
Is there any chance this component could ingest user data? I see we are sanitizing markdown, but still, you can inject images, new elements etc. If so, we should slap a big warning on it or make the markdown an optional switch.

**Comment by LucianBuzzo** [comment]
@JackuB What is your concern? Are you worried this could break layout?

**Comment by JackuB** [comment]
@LucianBuzzo one concern is definitely XSS, the other would be unintended formatting. For example if a project/team/… name could get rendered there, then from my `team_project_env` naming scheme is <code>team<em>project</em>env</code>.

**Comment by LucianBuzzo** [comment]
@JackuB The input is sanitized and we use GitHub flavoured markdown, so your `team_project_env` example would be rendered correctly.

**Pull request merged**
