### PR TITLE
Markdown: Allow the GitHub markdown wrapper to be imported separately

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Exporting the styled wrapper seperately allows you to user pre-parsed
markdown instead of having to render the markdown client-side.

Change-type: minor
Signed-off-by: Lucian <lucian.buzzo@gmail.com>

---
##### Contributor checklist

- [ ] I have rebuilt the README with `npm run build:docs`
- [ ] I have regenerated screenshots for any affected components with `npm run generate-screenshots`
- [ ] I have regenerated jest snapshots for any affected components with `npm run jest -- -u`

##### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)
---

### CODE REVIEW

**Comment by LucianBuzzo** [comment]
@sradevski I want to pre-process the markdown server-side, but still render the resulting HTML in the same style. 
Now that I think about it, maybe we want the markdown styles used here to be global "rendition" styles? Lets talk about this further at a later date.

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by dimitrisnl** [comment]
@LucianBuzzo 	were the tests failing for no reason?

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@dimitrisnl There was an incident on balena CI that stopped jobs from running, so I now need to trigger them to run again

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Pull request merged**
