### PR TITLE
Fix flexbox documentation URL in Flex README

### PR DESCRIPTION
**Pull request by Betree**
Markdown reference links are standardized as `[Link name][link-id]`, not `[Link name](link-id)`

See https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links

### CODE REVIEW

**Comment by Betree** [comment]
Hi @LucianBuzzo I just amended my commit. It would be nice to have this info in [CONTRIBUTING.md](https://github.com/resin-io-modules/rendition/blob/master/CONTRIBUTING.md) :wink:

**Comment by LucianBuzzo** [comment]
@Betree very true! Our contribution guidelines are woefully lacking at the moment. This is an open issue that I want to tackle soon https://github.com/resin-io-modules/rendition/issues/464

**Comment by LucianBuzzo** [comment]
@resin-ci retest

**Comment by LucianBuzzo** [comment]
@Betree I've spoken to our DevOps team and apparently there is an open issue with our CI process that prevents the checks from running when a PR is sent from a forked repo. We should have it resolved in the next week. I'll keep an eye on things and update you once the issue is resolved, at which point you'll need to rebase this PR onto master and then it can be merged.

**Comment by Betree** [comment]
Ok @LucianBuzzo, I'll wait for your message.

**Comment by LucianBuzzo** [comment]
@resin-ci retest

**Comment by LucianBuzzo** [comment]
@Betree Our CI issues are resolved, would you please rebase your PR on top of the current master branch?

**Comment by LucianBuzzo** [comment]
@Betree Sorry for the lack of attention on this PR - we've been very busy with the resin --> balena name change! If you can rebase your PR on top of master and I'll get this merged ASAP.

**Comment by LucianBuzzo** [comment]
@resin-ci retest

**Comment by sradevski** [comment]
Fixed by #652

**Pull request closed without merging**
