### PR TITLE
Update JellyForm dependencies

### PR DESCRIPTION
**Pull request by cyplo**
* rjsf
* temen
* jellyschema

### CODE REVIEW

**Comment by cyplo** [comment]
There is some incompatibility in the ts types - looking into that.

**Comment by cyplo** [comment]
New `@types/rjsf` needs new react types definitions and then there is a rabbit hole of fixing our code compat with new react TS types - let me see if we could not update the TS types for rjsf for now and have this still working -  would prefer to do the TS stuff upgrade in the separate PR

**Comment by cyplo** [comment]
@resin-ci retest

**Comment by cyplo** [comment]
@resin-ci retest

**Comment by nazrhom** [comment]
@resin-ci retest

**Pull request merged**
