### PR TITLE
Fix files that are missing from build output

### LINKED ISSUE #842: Can't import Mermaid component
https://codesandbox.io/s/l0nlp9yzm?fontsize=14

Importing the mermaid component gives the error `Could not find module`

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Fixes #842

### CODE REVIEW

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by thgreasi** [comment]
Crossposting from FD
> @lucianbuzzo, any context on why we removed the BadgeSelect & FilterForm components? This sounds like a major change. Isn't it?

**Comment by LucianBuzzo** [comment]
@thgreasi, The `FilterForm` component was internal to the `Form` component and was never exposed, and the `BadgeSelect` component was actually removed from the export in a previous major version bump but the core file never got deleted.

**Comment by nazrhom** [comment]
@balena-ci retest

**Pull request merged**
