### PR TITLE
DropDownButton should map through children correctly

### PR DESCRIPTION
**Pull request by karaxuna**
Change-type: minor
Connects-to: #661

### CODE REVIEW

**Comment by karaxuna** [comment]
@thgreasi I changed test to:

```javascript
/* globals expect, test */
import React from 'react'
import renderer from 'react-test-renderer'
import Provider from '../../src/components/Provider'
import DropDownButton from '../../src/components/DropDownButton'

test('DropDownButton renders correctly', () => {
  const component = renderer.create(
    <Provider>
      <DropDownButton primary label={<div>DropDown</div>}>
        <div>Item</div>
        {Array(3).map((_, index) => (
          <div key={index}>Item</div>
        ))}
      </DropDownButton>
    </Provider>
  )
  let tree = component.toJSON()
  expect(tree).toMatchSnapshot()
})
```
But tests still pass, even if I write `Item3` in place of `Item` it does not care.

**Comment by LucianBuzzo** [comment]
@karaxuna This is because of the list not being rendered until the button is clicked. If you look at the existing snapshot, there are no menu items in it https://github.com/balena-io-modules/rendition/blob/master/__tests__/components/__snapshots__/DropDownButton.spec.js.snap

**Comment by thgreasi** [comment]
@karaxuna  Let's keep the existing test case and write a new one that simulates a click to the dropdown and checks the children rendered with enzyme (like we do elsewhere) or maybe with https://reactjs.org/docs/test-utils.html .

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by thgreasi** [comment]
@resin-ci retest

**Pull request merged**
