### PR TITLE
Add a "position" prop to the Modal

### PR DESCRIPTION
**Pull request by sradevski**
Allowing the modal to be top-aligned is better
when the modal can expand vertically. If center-aligned
the modal expands in both directions, resulting in a bad
jumping UX. Setting the modal as top-aligned eliminates that
as the modal will only expand in the -y direction

Any comments or objections?

Change-type: minor
Signed-off-by: Stevche Radevski <stevche@balena.io>

Connects-to: # 
See: <url> 
Depends-on: <url> 
Change-type: major|minor|patch 

---
##### Contributor checklist

- [ ] I have rebuilt the README with `npm run build:docs`
- [ ] I have regenerated screenshots for any affected components with `npm run generate-screenshots`
- [ ] I have regenerated jest snapshots for any affected components with `npm run jest -- -u`

##### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)
---

### CODE REVIEW

**Comment by LucianBuzzo** [comment]
@sradevski what are your thoughts on making the modal *always* top align?

**Comment by sradevski** [comment]
@LucianBuzzo I find it center-aligned to look much better, and is better UX-wise as you would expect the main content (which would be the Modal) to be in the middle of your screen. The only time when top-aligned makes sense is when the modal content grows dynamically. Let's also talk with the designers and see what they think.

**Comment by LucianBuzzo** [comment]
@sradevski it seems to me that there are specific situations where you should always choose to top align the modal, otherwise the modal should always be center aligned. Is it possible to have the modal automatically use the best layout? Otherwise we are sort of setting a trap!

**Comment by sradevski** [comment]
@LucianBuzzo yeah it is, and I don't really like it, and I was expecting some suggestions TBH 😄 . I was just thinking a bit more about this, and I think I found a great solution. The modal jumping on resize can also be eliminated if we animate the modal resize, which will appear much smoother. I will try it out tomorrow and see how it goes.

**Comment by sradevski** [comment]
It turns out, animating auto-calculated height is not supported, so it will need a bit more work. I will close this PR in favor of this issue: https://github.com/balena-io-modules/rendition/issues/1049

**Pull request closed without merging**
