### PR TITLE
Make spinner use tertiary color

### PR DESCRIPTION
**Pull request by sradevski**
Change-type: patch
Signed-off-by: Stevche Radevski <stevche@balena.io>

---
##### Contributor checklist

- [ ] I have rebuilt the README with `npm run build:docs`
- [ ] I have regenerated screenshots for any affected components with `npm run generate-screenshots`
- [ ] I have regenerated jest snapshots for any affected components with `npm run jest -- -u`

##### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)
---

### CODE REVIEW

**Comment by iamsolankiamit** [comment]
I think we should have some screenshot testing for these.

**Comment by sradevski** [comment]
@iamsolankiamit updated

**Comment by iamsolankiamit** [comment]
the emphasised with label looks like it is off center, is that on purpose?

**Comment by sradevski** [comment]
@iamsolankiamit The reason that was centered was the spinner div took the entire width before, which was unintended as in many cases we want the spinner to be left-aligned (as discussed before). If you wish to center the spinner in a page, then you either pass the page as a child, or you center it manually.

**Pull request merged**
