### PR TITLE
components: Fix styled components' deprecation warning

### PR DESCRIPTION
**Pull request by dimitrisnl**
Connects-to: #724
Change-type: patch
Signed-off-by: Dimitrios Lytras <dimitrios@balena.io>

### CODE REVIEW

**Comment by dimitrisnl** [comment]
edit: my HEAD is a bit outdated. Fixing.

**Comment by dimitrisnl** [comment]
Hmm, this is particularly strange. There should be no visual changes. Investigating.

**Comment by sradevski** [comment]
@dimitrisnl I just saw that you updated the screenshot, but it seems something broke. I am assuming the place it broke is where we use `withComponent` to render things as a different tag from the original one. Let me know how things go (and re-add reviewers after a change so we get a notification) 😸

**Comment by dimitrisnl** [comment]
@sradevski 	I'm not very sure what's wrong. There shouldn't be any changes in the snapshots. 

Checking the `withComponent` instances but nothing wrong there. Any ideas?

**Comment by sradevski** [comment]
@dimitrisnl As I assumed, there was a problem with `withComponent` and the styles not being applied correctly to the anchor. I did some changes and pushed it, although didn't do any testing, so you might want to check it out a bit more before merging.

**Comment by dimitrisnl** [comment]
Sure, thanks

**Comment by sradevski** [comment]
@dimitrisnl Looking at the changed files, we probably don't want to pass all the props down to the HTML component (look at how the theme and other props are passed to the native HTML element).

**Comment by dimitrisnl** [comment]
This is getting a bit out of hand. The purpose was to change the deprecated syntax while extending a component. It shouldn't have spawned that many problems.

Will tweak it for couple minutes, and drop it if there is no progress. We shouldn't waste time on such a minor issue.

**Comment by sradevski** [comment]
@dimitrisnl I do agree, but when we decide to move to styled-components v4 we will have to do this anyway. It might be less relevant if we decide to use a different library though.

**Comment by LucianBuzzo** [comment]
@dimitrisnl Now that we've update to styled-components v4 can this PR be closed?

**Pull request closed without merging**
