### PR TITLE
Form: Support using null values in the widgets when it's valid type

### PR DESCRIPTION
**Pull request by thgreasi**
Change-type: minor
Signed-off-by: Thodoris Greasidis <thodoris@balena.io>

---
##### Contributor checklist

- [ ] I have regenerated screenshots for any affected components with `npm run generate-screenshots`
- [ ] I have regenerated jest snapshots for any affected components with `npm run jest -- -u`

##### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)
---

### CODE REVIEW

**Comment by grahammcculloch** [comment]
@thgreasi once it's building, I'd like to test the beta release of this in Jellyfish. IIRC we rely on `ui:value: null` to explicitly mean 'do not render this field at all'. We might need to rethink this but in any case I'm worried this change might result in us showing a whole load more (empty) fields in Jellyfish.

**Comment by thgreasi** [comment]
@grahammcculloch that sounds a bit inconsistent with what rjsf is doing for null values, isn't it?
See: https://rjsf-team.github.io/react-jsonschema-form/

The point of this PR was to support implementing a widget which is able to have its own handling for `null` values (eg show a special "unset" label with special formatting or something (something that default/emptyValue doesn't offer).
For null-able properties, that's just another valid value which we do need to render.

**Comment by grahammcculloch** [comment]
@thgreasi please ignore all my comments yesterday! I was remembering completely wrongly how we do things in Jellyfish. So I'm happy with these changes!

**Review by grahammcculloch — APPROVED** [review]
LGTM - we have an easy way in Jellyfish to deal with extra null value fields showing up, using the ui-schema.

**Pull request merged**
