### PR TITLE
[WIP] Exclude node 6 builds from CI

### PR DESCRIPTION
**Pull request by nazrhom**
Change-type: patch
Signed-off-by: Giovanni Garufi <giovanni@balena.io>

### CODE REVIEW

**Comment by JackuB** [comment]
Node 6 is still run in this PR - it needs to be merged?

**Comment by JackuB** [comment]
Ping @nazrhom

**Comment by JackuB** [comment]
Okay, let's try merging it and see whether that will update the checks

**Comment by nazrhom** [comment]
@sradevski @JackuB the check should be turned off on the PR, I noticed there is a bug in the CI that causes it to run anyway. I have a fix ready, will ping you on Monday once its deployed.

**Pull request merged**
