### PR TITLE
Improve README and documentation

### PR DESCRIPTION
**Pull request by sradevski**
Fixed all broken links in the readme

Connects-to: #609
Change-type: patch
Signed-off-by: Stevche Radevski <stevche@balena.io>

### CODE REVIEW

**Comment by sradevski** [comment]
@resin-ci retest

**Comment by sradevski** [comment]
@resin-ci retest

**Comment by sradevski** [comment]
@resin-ci retest

**Comment by LucianBuzzo** [comment]
@resin-ci retest

**Comment by sradevski** [comment]
@LucianBuzzo the build was failing several times, I tried removing the "engines" field from package.json and see if that was the reason. It was timing out all the time for some reason.

**Pull request merged**
