### PR TITLE
Allow specifying the filter components rendering order

### PR DESCRIPTION
**Pull request by sradevski**
There are a couple of files that changed due to running prettify. We need the flexibility to specify the order in order to make the new dashboard designs implementable. This also makes the search input component flex to the entire available width, so it appears better on larger screens. We can discuss whether this is preferable or not.

Note: The screenshots change all the time due to some small glitches, I am working on fixing it in a separate branch.

Change-type: minor
Signed-off-by: Stevche Radevski <stevche@balena.io>

---
##### Contributor checklist

- [ ] I have rebuilt the README with `npm run build:docs`
- [ ] I have regenerated screenshots for any affected components with `npm run generate-screenshots`
- [ ] I have regenerated jest snapshots for any affected components with `npm run jest -- -u`

##### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)
---

### CODE REVIEW

**Comment by dimitrisnl** [comment]
@sradevski 	Can you share the branch you mentioned?

**Comment by LucianBuzzo** [comment]
@sradevski Is there a reason for not simply changing the render order? I feel like we're adding a lot of additional complexity that isn't necessarily needed.

**Comment by sradevski** [comment]
@LucianBuzzo If we decide that we want the same order everywhere, I agree that it is better to simply change the ordering, I was just trying to preserve the existing behavior to isolate the change.

**Comment by LucianBuzzo** [comment]
@sradevski Lets keep it the same everywhere

**Comment by sradevski** [comment]
@LucianBuzzo @dimitrisnl I will pause this until the UI convergence to decide on the ordering of the filters.

**Comment by sradevski** [comment]
This is not necessary as of now, closing

**Pull request closed without merging**
