### PR TITLE
Generate fresh screenshots

### PR DESCRIPTION
**Pull request by corysimmons**
- cloned repo
- `npm ci` to do a clean install of node packages
- `npm run generate-screenshots` to generate screenshots from clean Docker container

This is what the screenshots should be unless I'm missing something.

Change-type: patch

---
##### Contributor checklist
- [x] I have rebuilt the README with `npm run build:docs`
- [x] I have regenerated screenshots for any affected components with `npm run generate-screenshots`
- [x] I have regenerated jest snapshots for any affected components with `npm run jest -- -u`

##### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)
---

### CODE REVIEW

**Comment by corysimmons** [comment]
@sradevski `Change-type: patch` is in the PR message. Does this need to be applied to the commit message itself?

**Comment by sradevski** [comment]
@corysimmons Per the contributing readme, the commit itself should contain the footer. You can refer to our process repo for more details on this.

**Comment by corysimmons** [comment]
Seems like the new screenshots are the same but a bit (~`5px`) taller for whatever reason.

**Comment by corysimmons** [comment]
Cleaned up the commit message according to https://github.com/balena-io-modules/rendition/blob/master/docs/COMMIT-GUIDELINES.md

**Pull request merged**
