### PR TITLE
Table horizontal scroll issue fixed

### PR DESCRIPTION
**Pull request by karaxuna**
Resolves: #625
Change-type: minor
Signed-off-by: Kakhaber Bazerashvili <kakhaber@resin.io>

### CODE REVIEW

**Comment by dimitrisnl** [comment]
@karaxuna 	Please take a look at the [commit guidelines](https://github.com/resin-io-modules/rendition/blob/master/docs/COMMIT-GUIDELINES.md). It will fix the `ResinCI/check-commits/commits` test.

(The linter repo can be found [here](https://github.com/resin-io/resin-commit-lint) if you're interested)

**Comment by dimitrisnl** [comment]
@karaxuna 	You might want to run `npm ci` btw

**Comment by karaxuna** [comment]
> @karaxuna You might want to run `npm ci` btw

Why?

**Comment by LucianBuzzo** [comment]
@karaxuna `npm ci` will ensure (hopefully) that you have the same set of npm packages on your local machine that produced the snapshots you are checking against. Its possible that different npm versions/installation methods could result in the snapshot being slightly different (`styled-components` and its ecosystem are the usual culprits for this).
It's also worth mentioning that the snapshots are our "canaries". If they show a conflict, but the other tests pass and a manual test of the components checks out then I'm happy to update the snapshot and continue.

**Comment by karaxuna** [comment]
tmp

**Pull request merged**
