### PR TITLE
docs: fix up misleading Swatches link

### PR DESCRIPTION
**Pull request by xginn8**
Change-type: patch
Signed-off-by: Matthew McGinn <matthew@balena.io>

### CODE REVIEW

**Comment by xginn8** [comment]
i did it again :)

**Comment by dimitrisnl** [comment]
Let's make sure to deploy storybook, since these changes won't be automatically available

**Comment by xginn8** [comment]
@dimitrisnl how shall we deploy storybook? is that something i can self-serve?

**Comment by dimitrisnl** [comment]
Hmm, it's good. I'll keep an eye on it and deploy it myself. Essentially we run the deploy script locally as there is something wrong with our pipeline atm.

**Pull request merged**
