### PR TITLE
docs: Fix incorrect Table prop name

### PR DESCRIPTION
**Pull request by mkoziarski**
#622

### CODE REVIEW

**Comment by LucianBuzzo** [comment]
@mkoziarski thankyou very much for your contribution! Could you please update your commit to include a `Change-type` footer? (see our freshly added commit guidelines here https://github.com/resin-io-modules/rendition/blob/master/docs/COMMIT-GUIDELINES.md )

**Comment by mkoziarski** [comment]
@LucianBuzzo, thank you for pointing the guidelines out to me. I've pushed the change again with the footer.

**Comment by LucianBuzzo** [comment]
@resin-ci retest

**Comment by LucianBuzzo** [comment]
@resin-ci retest

**Comment by LucianBuzzo** [comment]
@resin-ci retest

**Comment by LucianBuzzo** [comment]
@mkoziarski Sorry for the lack of attention on this PR - we've been very busy with the `resin --> balena` name change! If you can rebase your PR on top of master and I'll get this merged ASAP.

**Pull request merged**
