### PR TITLE
Form: Refactor extra widgets to work with tree-shaking

### LINKED ISSUE #914: Importing markdown and mermaid form widgets fails in webpack
Using webpack in production mode causes the markdown and mermaid form widgets to be ignored when loaded using:
```
import 'rendition/dist/extra/Form/markdown'
import 'rendition/dist/extra/Form/mermaid'
```
This is due to treeshaking and the `sideEffects: false` value in rendition's package.json

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Fixes #914

Change-type: patch
Signed-off-by: Lucian <lucian.buzzo@gmail.com>

Connects-to: # 
See: <url> 
Depends-on: <url> 
Change-type: major|minor|patch 

---
##### Contributor checklist

- [ ] I have rebuilt the README with `npm run build:docs`
- [ ] I have regenerated screenshots for any affected components with `npm run generate-screenshots`
- [ ] I have regenerated jest snapshots for any affected components with `npm run jest -- -u`

##### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)
---

### CODE REVIEW

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by thgreasi** [comment]
Otherwise, we could preserve the existing way of importing w/o explicit registration by modifying the package.json to:
```
"sideEffects": [
    "./dist_esm5/extra/Form/markdown.js"
    "./dist_esm5/extra/Form/mermaid.js
  ],
```

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Pull request merged**
