### PR TITLE
Update steps for running the storybook

### PR DESCRIPTION
**Pull request by FidelVe**
Hi!..

I'm currently playing around with `rendition`. After cloning the repo, when I tried to run the interactive storybook by following the steps I got the following Error:

```
ERROR in ./src/stories/swatches.story.js 
Module not found: Error: Can't resolve '../../dist' 
```

Is pretty simple, the `dist` folder doesn't exist yet when you have a fresh cloned copy straight from the repo, to fix this we just need to run `npm run build` before running `npm run start`, so I figured it would be good to have that extra step in here.

Connects-to: # 
See: <url> 
Depends-on: <url> 
Change-type: major|minor|patch 

---
##### Contributor checklist

- [ ] I have rebuilt the README with `npm run build:docs`
- [ ] I have regenerated screenshots for any affected components with `npm run generate-screenshots`
- [ ] I have regenerated jest snapshots for any affected components with `npm run jest -- -u`

##### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)
---

### CODE REVIEW

**Comment by LucianBuzzo** [comment]
Thanks for the contribution @FidelVe ! Please add a `Change-type` footer to your commit message as per our [guidelines](https://github.com/balena-io-modules/rendition/blob/master/docs/COMMIT-GUIDELINES.md) and I'll merge this :+1:

**Comment by FidelVe** [comment]
Done!

**Comment by sradevski** [comment]
@balena-ci retest

**Comment by sradevski** [comment]
@FidelVe There is a small mistake in the commit, the `change-type: patch` should be `Change-type: patch`.

**Comment by FidelVe** [comment]
Sorry for that typo!

**Comment by FidelVe** [comment]
@sradevski 

> @FidelVe There is a small mistake in the commit, the `change-type: patch` should be `Change-type: patch`. Also, you'll have to rebase against master when you get the chance.

rebased against master's ce05f97 and fixed the typo.

**Comment by sradevski** [comment]
@FidelVe I just merged something, sorry about that. Can you please rebase it, and I will merge it straight away. Cheers!

**Comment by FidelVe** [comment]
> @FidelVe I just merged something, sorry about that. Can you please rebase it, and I will merge it straight away. Cheers!

Don't worry is no trouble at all :smile: 

Rebased against master 69952f

**Comment by sradevski** [comment]
@balena-ci retest

**Pull request merged**
