### PR TITLE
test: Updated snapshots caused by npm dependency  updates

### PR DESCRIPTION
**Pull request by grahammcculloch**
Change-type: patch
Signed-off-by: Graham McCulloch <graham@balena.io>

---

Note - no updates to any source code or explicit updates to dependencies. But a bunch of snapshot updates!

##### Contributor checklist
- [ ] I have rebuilt the README with `npm run build:docs`
- [x] I have regenerated screenshots for any affected components with `npm run generate-screenshots`
- [x] I have regenerated jest snapshots for any affected components with `npm run jest -- -u`

##### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)
---

### CODE REVIEW

**Comment by grahammcculloch** [comment]
@balena-ci retest

**Comment by grahammcculloch** [comment]
@balena-ci retest

**Comment by grahammcculloch** [comment]
These screenshot tests are crazy! No changes when I run it locally. But each time the CI task runs, there are different failing (changed) screenshots!

**Comment by sradevski** [comment]
@balena-ci retest

**Comment by sradevski** [comment]
@grahammcculloch rendition only listens to me it seems 😄

**Pull request merged**
